### ISSUE TITLE
Assigning variables

### ISSUE THREAD

**Issue by Youngestdev** [anoniscoding/yorlang#19]
From the docs, the assigning of variables goes thus:

```
ti abd = "abd"
```

But, `ti` in Yoruba actually means *if* that's If I'm not mistaking and let ( which I assume you translated to ti ) should be `jẹki` instead. Lmk know your thoughts. I was thinking of fixing and sending a PR but it's wise to discuss it first.

**Comment by apjoex** [comment]
True

**Comment by koryoesz** [comment]
Jeki is very perfect

**Comment by Youngestdev** [comment]
Ok.cool.

**Comment by Youngestdev** [comment]
Haha nice!

**Comment by anoniscoding** [comment]
Yeah, i've changed it in the latest version(1.0.5) to jeki

**Comment by anoniscoding** [comment]
thanks @Youngestdev
