### ISSUE TITLE
Helper: Random Number Generation

### ISSUE THREAD

**Issue by mykeels** [anoniscoding/yorlang#53]
**Is your feature request related to a problem? Please describe.**
I can't find a way to generate random numbers

**Describe the solution you'd like**
A helper function that takes in 2 parameters representing the lower and upper limit of a generated random number.

> I'm not sure what such a function would be called, but google translate suggests `yipo`. Are there better alternatives?

**Comment by anoniscoding** [comment]
```yipo``` is cool. Looking forward to the PR

**Comment by AfolabiOlaoluwa** [comment]
‪This nice and hard to think of 😃. I think something like..‬
‪iyipada()‬
‪yiipada()‬
‪yii_pada()‬
‪yii_po() ~ turn_it()‬

**Comment by AfolabiOlaoluwa** [comment]
I will still think about it if we can have a better word for that function
